### ISSUE TITLE
Unhandled exception. System.ArgumentException: The key 'class Parent' does not exist in the dictionary. (Parameter 'key')

### ISSUE THREAD

**Issue by Zeon8** [jfd16/Mariana#2]
Hello, experimented with inheritance and got an error
```
Unhandled exception. System.ArgumentException: The key 'class Parent' does not exist in the dictionary. (Parameter 'key')
   at Mariana.Common.ReferenceDictionary`2.getValueRef(TKey key, Boolean createIfNotExists) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.Common\src\ReferenceDictionary.cs:line 162
   at Mariana.Common.ReferenceDictionary`2.get_Item(TKey key) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.Common\src\ReferenceDictionary.cs:line 74
   at Mariana.AVM2.Compiler.ScriptCompileContext._createClassDefIfInContext(Class klass) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Compiler\ScriptCompileContext.cs:line 512
   at Mariana.AVM2.Compiler.ScriptCompileContext._createClassDefIfInContext(Class klass) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Compiler\ScriptCompileContext.cs:line 540
   at Mariana.AVM2.Compiler.ScriptCompileContext.compileFile(ABCFile file) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Compiler\ScriptCompileContext.cs:line 249
   at Mariana.AVM2.Compiler.ScriptLoader.compile(ABCFile abcFile) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Compiler\ScriptLoader.cs:line 68
```
Example code:
```actionscript
// Parent.as
public class Parent {}
// Child.as
public class Child extends Parent {}

// Main.as
public class Main
{
    public static function main():void 
    {
        new Child();
    }
}
```

**Comment by jfd16** [comment]
Can you attach the binary file (ABC) that is causing this issue?

**Comment by Zeon8** [comment]
Yes, [here](https://github.com/jfd16/Mariana/files/6988441/acs.zip)

**Comment by Zeon8** [comment]
Yes, [here](https://github.com/jfd16/Mariana/files/6988465/project-2.zip)

**Comment by jfd16** [comment]
The file that you have provided does not contain a definition for the `Parent` class, so I suppose that it is defined in another file that has been compiled separately.

This case has been fixed: https://github.com/jfd16/Mariana/commit/d11915705a54d4620d11740911bd39b13e131116
