### ISSUE TITLE
Error when instantiating objects

### ISSUE THREAD

**Issue by Zeon8** [jfd16/Mariana#3]
After fix #2 I tried to run this example:
```actionscript
// Test.as
public class Test { }

// Main.as
public class Main
{
   public static function main():void 
   {
      new Test();
   }	
}
```
And got an error:
```
Process terminated. Assertion failed.
   at Mariana.AVM2.Core.MethodTrait.get_underlyingMethodInfo() in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Core\MethodTrait.cs:line 51
   at Mariana.AVM2.Core.RuntimeDispatch.generateMethodStub(MethodTrait method) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Core\RuntimeDispatch.cs:line 209
   at Mariana.AVM2.Core.MethodTrait.<.ctor>b__10_0() in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Core\MethodTrait.cs:line 39
   at Mariana.Common.LazyInitObject`1._internalGetValue() in E:\Work\Programing\NetProjects\Mariana-main\Mariana.Common\src\LazyInitObject.cs:line 179
   at Mariana.AVM2.Core.MethodTrait.tryInvoke(ASAny target, ASAny receiver, ReadOnlySpan`1 args, ASAny& result) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Core\MethodTrait.cs:line 226
   at Mariana.AVM2.Core.Trait.invoke(ASAny target, ASAny receiver, ReadOnlySpan`1 args) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Core\Trait.cs:line 225
   at Mariana.AVM2.Core.Trait.invoke(ASAny target, ReadOnlySpan`1 args) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Core\Trait.cs:line 214
   at Mariana.AVM2.Core.Trait.invoke(ReadOnlySpan`1 args) in E:\Work\Programing\NetProjects\Mariana-main\Mariana.AVM2\src\Core\Trait.cs:line 251
```

**Comment by jfd16** [comment]
Can you please provide the ABC files and the code used to compile them, so that this can be reproduced?

**Comment by Zeon8** [comment]
[project.zip](https://github.com/jfd16/Mariana/files/7005278/project.zip)

**Comment by jfd16** [comment]
Fixed in https://github.com/jfd16/Mariana/commit/9e2db3f8cd3db973ee73d1afff451c83870c09aa
